version: 0.2

phases:
  build:
    commands:
      - yum install tar gzip pandoc texlive-latex -y
      - curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.111.2/hugo_0.111.2_linux-arm64.tar.gz
      - tar xvpf hugo_0.111.2_linux-arm64.tar.gz
      - ./hugo
      - pandoc --pdf-engine pdflatex content/index.md -o public/data/cv_jesus_colino.pdf
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
